### ISSUE TITLE
Password reset fakes sending of email

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#65]
I try to do a password reset online...but I actually don't get any reset email

**Comment by ghost** [comment]
That should be because you are not a registered user. Ope's login feature
has not been merged in.

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/

On Tue, Oct 20, 2015 at 9:42 PM, Otemuyiwa Prosper <notifications@github.com

**Comment by ghost** [comment]
Oh. I just noticed it now. I think I have to remove the .env from the
.gitignore. Or is there a better way?

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
I have merged everyone's feature in and everything works. I have also registered but when I try to do a password reset I don't get an email

**Comment by ghost** [comment]
It may be because of the SendGrid settings in the .env.

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/

On Tue, Oct 20, 2015 at 9:57 PM, Otemuyiwa Prosper <notifications@github.com

**Comment by unicodeveloper** [comment]
Shed more light on that

**Comment by ghost** [comment]
Details like MAIL_DRIVER, MAIL_HOST, MAIL_USERNAME, MAIL_PASSWORD &
MAIL_PORT are in my .env file. I think that might be what's stopping it
from sending because it sends on my system.

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/

On Tue, Oct 20, 2015 at 9:59 PM, Otemuyiwa Prosper <notifications@github.com

**Comment by unicodeveloper** [comment]
Wow, then of course it wouldnt send because heroku has no idea about those constants, it has to be registered on the heroku dashboard as environment variables

**Comment by ghost** [comment]
So we push .env file then. Okay.

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
No..you don't push the .env file, all we need to do is just register those constants on the server via heroku dashboard.

**Comment by unicodeveloper** [comment]
Slack me the constants and their values

**Comment by ghost** [comment]
Okay. I am on it.

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/
